platform :ios ,'6.0'

pod 'MagicalRecord','~>2.0'
pod 'SDWebImage','~>3.7'
pod 'MJRefresh','~>1.3'
pod 'MBProgressHUD','~>0.9'
pod 'AFSoundManager','~>2.1'
pod 'PureLayout','~>2.0.4'
pod 'ReactiveCocoa','~>2.4.7'
pod 'SVWebViewController','~>1.0'
pod 'NJKWebViewProgress','~>0.1.8'
pod 'AFNetworking','~>2.5.1'
