platform :ios ,'7.0'

pod 'MagicalRecord','2.2'
pod 'SDWebImage','~>3.7'
pod 'MJRefresh','~>1.3'
pod 'DOUAudioStreamer','~>0.2.9'
pod 'PureLayout','~>2.0.4'
pod 'ReactiveCocoa','~>2.4.7'
pod 'SVWebViewController','~>1.0'
pod 'NJKWebViewProgress','~>0.1.8'
pod 'AFNetworking','~>2.5.1'
pod 'Reachability','~>3.2'
pod 'TMCache' ,'~>1.2.4'
pod 'MBProgressHUD','~>0.9.1'
pod 'MJExtension','~>1.0.0'
pod 'UIActivityIndicator-for-SDWebImage','~>1.2'
pod 'NHBalancedFlowLayout' ,'~>0.2'
