platform :ios ,'6.0'

pod 'MagicalRecord','~>2.0'
pod 'SDWebImage','~>3.7'
pod 'MJRefresh','~>1.3'
pod 'SpinKit','~>1.0'
pod 'DOUAudioStreamer','~>0.2.9'
pod 'PureLayout','~>2.0.4'
pod 'ReactiveCocoa','~>2.4.7'
pod 'SVWebViewController','~>1.0'
pod 'NJKWebViewProgress','~>0.1.8'
pod 'AFNetworking','~>2.5.1'
pod 'ZBarSDK','~>1.2'
pod 'Reachability','~>3.2'
pod 'TMCache' ,'~>1.2.4'
